import Link from "next/link";
import { ArrowRight, CalendarDays, Clock3 } from "lucide-react";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { Button } from "@/components/ui/button";
import { Reveal } from "@/components/ui/reveal";
import { JsonLd } from "@/components/seo/json-ld";
import { blogArticles } from "@/lib/seo-local-data";

const guidance: Record<string, { intro: string; sections: [string, string][] }> = {
  "pourquoi-creer-un-site-internet-en-2026": { intro: "Les plateformes changent, les algorithmes sociaux réduisent la portée et les réponses générées par l’IA transforment la recherche. Pourtant, le site demeure l’espace numérique que l’entreprise possède réellement.", sections: [["Un actif plutôt qu’un profil", "Un site permet de maîtriser le récit, les données, la conversion et la relation avec les visiteurs. Il rassemble les preuves, répond aux objections et reste accessible sans dépendre du format imposé par une plateforme."], ["La confiance avant la conversion", "Les prospects vérifient la cohérence d’une entreprise : qualité du site, avis, coordonnées, réalisations et expertise. Une expérience rapide et accessible agit comme une démonstration silencieuse du niveau d’exigence."], ["Être compris par Google et par l’IA", "Une architecture claire, des auteurs identifiés, des contenus documentés et des données structurées aident les moteurs à relier une marque à ses sujets. La qualité éditoriale devient plus importante que la répétition de mots-clés."]] },
  "combien-coute-un-site-internet": { intro: "Le prix d’un site ne correspond pas à un nombre de pages. Il rémunère une réflexion stratégique, une direction artistique, une architecture, du contenu, du développement et une capacité à produire des résultats.", sections: [["Les postes qui construisent le prix", "Cadrage, recherche utilisateur, UX, UI, développement, intégration, SEO, migration et recette constituent des métiers distincts. Un projet économique réduit nécessairement certains de ces postes ; un devis sérieux rend ces arbitrages visibles."], ["Template ou création sur mesure", "Un thème peut convenir à un lancement très simple. Le sur-mesure devient pertinent lorsque l’image, la conversion, les performances ou des processus métiers comptent réellement. Il évite également l’accumulation d’extensions difficiles à maintenir."], ["Penser en coût de possession", "Hébergement, maintenance, évolutions et production de contenu doivent être anticipés. Un site peu cher mais lent, fragile ou impossible à faire évoluer peut coûter davantage qu’une base saine."]] },
  "site-vitrine-ou-e-commerce": { intro: "Le bon choix dépend moins du nombre de produits que du modèle de vente, de la logistique, de la fréquence d’achat et du niveau d’accompagnement attendu par le client.", sections: [["Le rôle du site vitrine", "Il présente une expertise, rassure, qualifie la demande et facilite le contact. Il convient aux services, artisans, professions libérales, industries et offres dont la vente nécessite un échange."], ["Les exigences du commerce en ligne", "Catalogue, paiement, livraison, taxes, retours, gestion des stocks, emails transactionnels et service client forment un système. L’expérience doit réduire les hésitations sans masquer les informations obligatoires."], ["Une progression possible", "Une architecture bien conçue peut commencer par une vitrine, tester l’intérêt pour certaines offres puis intégrer une vente en ligne. Cette trajectoire limite le risque et utilise les données réelles."]] },
  "pourquoi-seo-local-indispensable": { intro: "Une recherche locale exprime souvent un besoin immédiat. Être visible au bon endroit et au bon moment rapproche directement le référencement du chiffre d’affaires.", sections: [["Site et fiche d’établissement", "Google Business Profile apporte une présence cartographique ; le site développe les services, les preuves et les réponses. Les deux doivent partager des coordonnées, catégories et informations cohérentes."], ["La pertinence territoriale", "Une page locale utile décrit la zone réellement desservie, les contraintes, les cas clients et les questions propres au marché. Une série de textes interchangeables n’apporte ni confiance ni avantage durable."], ["Mesurer les actions", "Appels, itinéraires, formulaires et réservations permettent d’évaluer le SEO local. Les positions seules ne disent pas si la visibilité produit des opportunités."]] },
  "comment-choisir-agence-web": { intro: "Une bonne agence ne vend pas d’abord un écran. Elle cherche à comprendre le modèle économique, le public, la différence et la manière dont le projet sera mesuré.", sections: [["Évaluer la méthode", "Demandez qui mène la stratégie, qui conçoit, qui développe et comment se déroulent les validations. Une méthode claire protège les délais et permet de comprendre les décisions."], ["Regarder au-delà des images", "Les références doivent être rapides, accessibles, cohérentes sur mobile et capables d’expliquer une offre. Un portfolio spectaculaire ne suffit pas si les sites réels sont difficiles à utiliser."], ["Anticiper l’après-lancement", "Propriété des comptes, documentation, hébergement, sécurité, maintenance et capacité d’évolution doivent être définis avant de signer."]] },
  "erreurs-refonte-site": { intro: "Une refonte peut améliorer l’image tout en détruisant une partie du trafic si les contenus, les URL et les signaux accumulés ne sont pas étudiés avant le changement.", sections: [["Supprimer sans inventorier", "Les pages recevant des liens ou répondant à des recherches doivent être conservées, améliorées ou redirigées précisément. Une redirection générale vers l’accueil fait perdre le contexte."], ["Concevoir avant de comprendre", "Commencer par une maquette sans analyser les parcours, les données et les objectifs reproduit souvent les mêmes problèmes sous une apparence différente."], ["Oublier la recette", "Formulaires, analytics, métadonnées, partage social, vitesse, clavier et appareils réels doivent être testés avant la bascule."]] },
  "ameliorer-referencement-google": { intro: "Le référencement progresse lorsque Google peut explorer le site, comprendre son sujet et constater qu’il apporte une réponse fiable et appréciée.", sections: [["Une base technique saine", "Indexation, canonicals, sitemap, performances, rendu mobile et liens internes constituent le socle. Les erreurs techniques ne se compensent pas par une multiplication d’articles."], ["Répondre à une intention", "Chaque page doit savoir à quelle question elle répond et quelle action elle facilite. Un contenu précis, illustré par l’expérience, est plus utile qu’un texte artificiellement long."], ["Construire l’autorité", "Réalisations, avis, citations locales, partenariats, auteurs et liens éditoriaux renforcent la confiance. Cette autorité se construit dans le temps."]] },
  "google-business-profile": { intro: "La fiche Google Business Profile est souvent la première interface entre une entreprise locale et un prospect. Son optimisation doit rester factuelle, régulière et cohérente avec le site.", sections: [["Catégories et services", "La catégorie principale décrit l’activité dominante. Les catégories secondaires et services complètent le contexte sans chercher à couvrir des métiers non exercés."], ["Avis et réponses", "Solliciter des avis authentiques après une prestation et répondre avec attention nourrit la confiance. Les réponses ne doivent pas devenir des listes de mots-clés."], ["Photos et informations", "Horaires, téléphone, zone, site, attributs et photos récentes réduisent la friction. Toute modification importante doit être répercutée partout."]] },
  "seo-pour-artisans": { intro: "Pour un artisan, le référencement doit montrer ce qui est fait, où, avec quel niveau de finition et comment obtenir rapidement une estimation.", sections: [["Montrer les réalisations", "Des photos optimisées, un contexte, les matériaux, la commune et le problème résolu transforment une galerie en preuve. Le consentement du client et des visuels originaux renforcent la crédibilité."], ["Clarifier la zone", "Les communes réellement desservies, les délais et les contraintes de déplacement doivent être lisibles. Des pages locales ne sont utiles que si elles apportent une information propre."], ["Faciliter la demande", "Téléphone visible, formulaire court, types de travaux et éléments à préparer réduisent les échanges inutiles et améliorent la qualité des demandes."]] },
  "seo-pour-restaurants": { intro: "Le parcours d’un client de restaurant est court : découverte, menu, avis, localisation, disponibilité et réservation. Chaque seconde et chaque information manquante peuvent interrompre ce parcours.", sections: [["Un menu accessible", "Le menu doit être lisible en HTML, actualisé et adapté au mobile. Un PDF lourd ou une photo empêche la recherche, l’accessibilité et parfois la décision."], ["Données et plateformes", "Restaurant, horaires, cuisine, fourchette de prix, réservation et adresse peuvent être balisés. Le site, Google et les plateformes doivent rester cohérents."], ["Créer une préférence", "Photos originales, histoire du lieu, chef, producteurs et ambiance donnent une raison de choisir. L’objectif n’est pas seulement d’être trouvé, mais désiré."]] },
  "seo-domaines-viticoles": { intro: "Un domaine viticole s’adresse aux acheteurs, visiteurs, professionnels et parfois à l’international. Le site doit réunir émotion, information et contraintes réglementaires.", sections: [["Raconter sans cliché", "Terroir, parcelles, pratiques, personnes et millésimes offrent une matière éditoriale unique. Une narration précise distingue davantage qu’un vocabulaire générique de tradition et d’excellence."], ["Développer l’œnotourisme", "Visites, accessibilité, langues, horaires, groupes, réservation et activités voisines doivent être anticipés. Le référencement associe alors l’appellation, le territoire et l’expérience proposée."], ["Vendre avec confiance", "Fiches détaillées, accords, livraison, conservation, paiement et service client rassurent. Les performances et la simplicité du tunnel sont essentielles sur mobile."]] },
};

export function BlogArticle({ slug, title, description }: { slug: string; title: string; description: string }) {
  const article = guidance[slug];
  const related = blogArticles.filter(item => item[0] !== slug).slice(0, 3);
  return (
    <>
      <JsonLd data={{ "@context": "https://schema.org", "@type": "Article", headline: title, description, datePublished: "2026-07-27", dateModified: "2026-07-27", author: { "@type": "Organization", name: "MRD Studio", url: "https://mrd-studio.fr" }, publisher: { "@id": "https://mrd-studio.fr/#business" }, mainEntityOfPage: `https://mrd-studio.fr/blog/${slug}`, image: "https://mrd-studio.fr/images/logo.png" }} />
      <Header />
      <main>
        <article>
          <header className="relative overflow-hidden pb-24 pt-44 sm:pt-52"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_30%,rgba(214,169,138,.1),transparent_40%),#050505]" /><div className="container-wide relative"><Link href="/blog" className="eyebrow">Le journal MRD</Link><h1 className="display mt-8 max-w-5xl text-[clamp(56px,8vw,116px)] leading-[.87] tracking-[-.055em]">{title}</h1><div className="mt-9 flex gap-6 text-[10px] uppercase tracking-[.14em] text-white/35"><span className="flex items-center gap-2"><CalendarDays size={13} /> 27 juillet 2026</span><span className="flex items-center gap-2"><Clock3 size={13} /> 7 min</span></div></div></header>
          <div className="container-wide grid gap-12 pb-28 lg:grid-cols-[.28fr_.72fr]"><aside className="hidden lg:block"><div className="sticky top-32 border-l border-accent/30 pl-5 text-[10px] uppercase tracking-[.14em] text-white/35">Expertise<br />MRD Studio</div></aside><div className="max-w-3xl"><p className="display text-3xl leading-[1.35] text-paper sm:text-4xl">{article.intro}</p>{article.sections.map(([heading, text], index) => <section key={heading} className="border-b border-white/10 py-12"><span className="text-[10px] text-accent">0{index + 1}</span><h2 className="display mt-4 text-4xl">{heading}</h2><p className="mt-6 text-[15px] leading-8 text-muted">{text}</p><p className="mt-5 text-[15px] leading-8 text-muted">Pour une entreprise du Grand Est, cette réflexion doit être reliée au territoire, aux attentes de ses clients et à ses ressources internes. La bonne décision n’est pas la plus spectaculaire : c’est celle qui reste cohérente, mesurable et utile dans la durée.</p></section>)}</div></div>
        </article>
        <section className="section-pad bg-panel"><div className="container-wide"><Reveal><p className="eyebrow mb-5">Continuer la lecture</p><h2 className="display text-5xl">Conseils <span className="text-accent">à appliquer.</span></h2></Reveal><div className="mt-12 grid gap-4 md:grid-cols-3">{related.map(([relatedSlug, relatedTitle, relatedDescription]) => <Link key={relatedSlug} href={`/blog/${relatedSlug}`} className="group rounded-[20px] border border-white/10 bg-ink p-7 transition-all hover:-translate-y-1 hover:border-accent/30"><h3 className="display text-2xl">{relatedTitle}</h3><p className="mt-4 text-xs leading-6 text-muted">{relatedDescription}</p><ArrowRight className="mt-8 text-accent transition-transform group-hover:translate-x-1" size={16} /></Link>)}</div></div></section>
        <section className="py-28 text-center"><Reveal className="container-wide"><h2 className="display text-6xl">Votre visibilité mérite une <span className="text-accent">stratégie.</span></h2><Button href="/contact" className="mt-9">Échanger avec le studio</Button></Reveal></section>
      </main>
      <Footer />
    </>
  );
}
