export type Department = {
  slug: string;
  name: string;
  code: string;
  capital: string;
  cities: string[];
  lead: string;
  economy: string;
  territory: string;
  opportunities: string;
  localSeo: string;
  approach: string;
  testimonial: { quote: string; author: string; company: string };
};

export const departments: Department[] = [
  {
    slug: "marne", name: "Marne", code: "51", capital: "Châlons-en-Champagne",
    cities: ["Reims", "Épernay", "Châlons-en-Champagne", "Vitry-le-François", "Sézanne", "Avize", "Fismes", "Tinqueux", "Cormontreuil", "Bétheny"],
    lead: "La Marne réunit des marchés que peu de territoires peuvent associer : une métropole universitaire à Reims, la capitale mondiale du Champagne à Épernay, une préfecture administrative à Châlons-en-Champagne et un réseau dense de communes où artisans, exploitations viticoles et PME travaillent souvent au-delà des frontières régionales. Un site efficace doit traduire cette diversité sans perdre la précision nécessaire au référencement local.",
    economy: "Le tissu marnais repose sur la viticulture et ses métiers connexes, l’agro-industrie, la logistique, le commerce, le tourisme de mémoire et un secteur tertiaire en croissance. Les maisons de Champagne n’ont pas les mêmes attentes qu’un artisan de Sézanne, un cabinet rémois ou une entreprise industrielle de Vitry-le-François. Nous construisons donc une stratégie éditoriale et une expérience distinctes, adaptées au cycle de décision de chaque activité.",
    territory: "Entre la Montagne de Reims, la Côte des Blancs, la vallée de la Marne et les plaines de Champagne crayeuse, l’identité locale est forte mais jamais uniforme. MRD Studio est implanté à Avize : cette proximité permet de comprendre les codes du territoire, les attentes d’une clientèle internationale et la nécessité de préserver une image premium sans tomber dans les clichés graphiques du monde viticole.",
    opportunities: "La concurrence numérique reste très inégale. De nombreuses entreprises reconnues disposent encore d’un site lent, difficile à consulter sur mobile ou incapable d’expliquer clairement leur valeur. Une refonte structurée offre un avantage mesurable : davantage de demandes qualifiées, une meilleure visibilité dans Google Maps, des contenus qui répondent aux recherches locales et une image cohérente avec la qualité réelle de l’entreprise.",
    localSeo: "Nous travaillons les requêtes liées aux communes, aux bassins d’activité et aux intentions concrètes. Une stratégie marnaise peut associer des pages de services, des études de cas, des contenus autour du Champagne ou du tourisme, des données structurées et une fiche Google Business Profile correctement reliée au site. L’objectif n’est pas de répéter le nom des villes, mais de démontrer une connaissance utile du marché.",
    approach: "Chaque projet commence par un audit de l’offre, de la concurrence locale et du parcours commercial. L’architecture est ensuite pensée pour guider un prospect depuis sa recherche jusqu’à la prise de contact. Design, développement Next.js, rédaction, SEO technique et mesure des conversions sont réunis dans une démarche unique, avec des performances élevées sur mobile comme sur ordinateur.",
    testimonial: { quote: "Une compréhension immédiate de notre univers et des enjeux propres à la Champagne. Le nouveau site génère des demandes beaucoup plus pertinentes.", author: "Claire M.", company: "Maison indépendante, Épernay" },
  },
  {
    slug: "aisne", name: "Aisne", code: "02", capital: "Laon",
    cities: ["Saint-Quentin", "Laon", "Soissons", "Château-Thierry", "Chauny", "Tergnier", "Hirson"],
    lead: "L’Aisne est un département de connexions : proche de l’Île-de-France, des Hauts-de-France, de la Champagne et de la Belgique, il offre aux entreprises un marché qui dépasse largement leurs communes d’implantation. À Saint-Quentin, Laon, Soissons ou Château-Thierry, une présence numérique solide permet de rendre cette position visible et de concurrencer des acteurs installés dans de plus grandes métropoles.",
    economy: "Industrie, sous-traitance, agriculture, bâtiment, transport, services aux entreprises et tourisme patrimonial composent une économie concrète, souvent portée par des PME familiales. Ces sociétés possèdent un savoir-faire remarquable mais peinent parfois à l’exprimer en ligne. Notre travail consiste à transformer leurs preuves, leurs méthodes et leur ancrage territorial en une expérience claire qui rassure les donneurs d’ordre comme les particuliers.",
    territory: "Le nord autour de Saint-Quentin et du Vermandois, le centre administratif laonnois, le Soissonnais et le sud tourné vers Château-Thierry ne partagent pas exactement les mêmes flux. Une architecture locale sérieuse respecte ces bassins de vie. Elle relie les contenus selon les zones réellement desservies et évite les pages artificielles qui n’apportent aucune information au lecteur.",
    opportunities: "Les recherches locales dans l’Aisne sont souvent très proches d’une décision : trouver un artisan disponible, comparer un prestataire B2B, réserver une adresse ou contacter une profession libérale. Un site rapide, accessible et documenté peut prendre une place importante face aux annuaires. Il devient un actif commercial autonome et non une simple carte de visite.",
    localSeo: "La stratégie associe la qualité des pages locales, la cohérence des coordonnées, les avis, le balisage LocalBusiness, la couverture des questions fréquentes et les liens avec Google Business Profile. Nous analysons aussi la manière dont les habitants nomment leur secteur, car les recherches peuvent viser une ville, une communauté d’agglomération ou un axe reliant plusieurs communes.",
    approach: "MRD Studio privilégie une méthode lisible : découverte des objectifs, hiérarchie des offres, prototype, direction artistique, développement, optimisation technique puis accompagnement. Les contenus sont écrits pour des personnes avant d’être interprétés par les moteurs. Cette exigence améliore simultanément l’EEAT, l’engagement et la conversion.",
    testimonial: { quote: "Le site explique enfin notre métier sans jargon. Nous sommes mieux trouvés et surtout contactés par les bons interlocuteurs.", author: "Julien D.", company: "PME industrielle, Saint-Quentin" },
  },
  {
    slug: "ardennes", name: "Ardennes", code: "08", capital: "Charleville-Mézières",
    cities: ["Charleville-Mézières", "Sedan", "Rethel", "Givet", "Nouzonville"],
    lead: "Des portes de Reims à la frontière belge, les Ardennes possèdent une identité industrielle, naturelle et transfrontalière singulière. Les entreprises de Charleville-Mézières, Sedan, Rethel, Givet ou Nouzonville peuvent utiliser le digital pour rendre leurs compétences visibles auprès d’une clientèle française et belge, attirer de nouveaux collaborateurs et mieux valoriser leur implantation.",
    economy: "La métallurgie, la fonderie, la mécanique, le bois, l’agriculture, le tourisme vert et le commerce constituent des piliers durables. Pour ces métiers, le design ne doit jamais masquer la preuve. Nous organisons les certifications, capacités de production, zones d’intervention, réalisations et engagements afin que chaque visiteur comprenne rapidement pourquoi choisir l’entreprise.",
    territory: "La vallée de la Meuse concentre des savoir-faire et des paysages très différents du sud du département tourné vers Rethel. Le référencement doit refléter ces réalités, y compris les recherches transfrontalières autour de Givet. Une page locale pertinente parle des usages, des distances, des marchés et des attentes propres à la zone plutôt que d’aligner des noms de communes.",
    opportunities: "De nombreux marchés industriels commencent désormais par une vérification en ligne, même lorsque la relation commerciale se construit ensuite par recommandation. Un site crédible confirme la solidité d’un fournisseur. Pour le tourisme ou les services, il réduit au contraire le temps entre la découverte et la réservation. Dans les deux cas, performance et clarté sont décisives.",
    localSeo: "Nous structurons les offres autour des intentions locales et professionnelles, puis nous renforçons leur crédibilité par des études de cas, des auteurs identifiés, des données structurées et des informations d’entreprise cohérentes. Les liens internes relient les pages géographiques aux expertises sans créer de répétition artificielle.",
    approach: "L’accompagnement combine stratégie, direction artistique, UX, développement Next.js et SEO. Les interfaces restent sobres, rapides et adaptées aux usages mobiles. Une attention particulière est portée à l’accessibilité, importante pour les collectivités et les entreprises souhaitant proposer une expérience fiable à tous leurs publics.",
    testimonial: { quote: "MRD Studio a réussi à donner une image contemporaine à un métier industriel très technique, sans perdre notre sérieux.", author: "Marc V.", company: "Entreprise de mécanique, Charleville-Mézières" },
  },
  {
    slug: "aube", name: "Aube", code: "10", capital: "Troyes",
    cities: ["Troyes", "Romilly-sur-Seine", "Nogent-sur-Seine", "Bar-sur-Aube", "Bar-sur-Seine"],
    lead: "L’Aube associe la puissance commerciale de Troyes, une tradition textile toujours influente, des activités industrielles et logistiques, les vignobles de la Côte des Bar et un patrimoine touristique reconnu. Cette pluralité crée des opportunités fortes pour les entreprises capables de présenter leur valeur avec un site rapide, distinctif et pensé pour les recherches locales.",
    economy: "Magasins de marque, textile, e-commerce, industrie, nucléaire, agriculture, Champagne, hôtellerie et restauration génèrent des parcours clients très différents. Un commerce troyen doit articuler visite physique et découverte en ligne ; un domaine de Bar-sur-Aube travaille l’image et l’œnotourisme ; une entreprise de Nogent-sur-Seine valorise plutôt ses compétences et sa fiabilité opérationnelle.",
    territory: "Troyes rayonne sur une grande partie du département, mais Romilly-sur-Seine, le Nogentais et la Côte des Bar possèdent leurs propres écosystèmes. Le contenu local doit comprendre ces polarités. Il peut également tirer parti de la proximité avec Paris, la Bourgogne et la Marne sans diluer la pertinence auboise.",
    opportunities: "Le niveau d’exigence visuelle des consommateurs progresse. Dans un territoire connu pour ses marques et son patrimoine, une interface générique peut réduire la confiance. À l’inverse, une expérience numérique précise permet de soutenir un positionnement premium, d’améliorer le panier moyen, de développer les réservations ou d’accélérer les demandes professionnelles.",
    localSeo: "Nous associons recherche sémantique, pages de services, contenus locaux, optimisation des images, données structurées et suivi des performances. Les requêtes saisonnières liées au tourisme, aux soldes, aux vendanges ou aux événements sont intégrées lorsque cela sert réellement l’activité. Chaque page possède une fonction claire dans le parcours.",
    approach: "Notre méthode part des données disponibles et des objectifs commerciaux. Le design est ensuite conçu sur mesure, puis développé avec une base technique rapide et maintenable. La mesure des formulaires, appels et actions importantes permet d’arbitrer les évolutions après la mise en ligne au lieu de travailler sur des impressions.",
    testimonial: { quote: "Le nouveau parcours rend notre offre beaucoup plus lisible. Les réservations directes ont progressé dès les premières semaines.", author: "Sophie R.", company: "Maison d’hôtes, Côte des Bar" },
  },
  {
    slug: "haute-marne", name: "Haute-Marne", code: "52", capital: "Chaumont",
    cities: ["Chaumont", "Langres", "Saint-Dizier", "Joinville", "Nogent"],
    lead: "La Haute-Marne dispose de compétences reconnues dans la métallurgie, la coutellerie, la fonderie, l’industrie, l’agriculture et le tourisme patrimonial. À Chaumont, Langres, Saint-Dizier, Joinville ou Nogent, le numérique peut réduire l’effet de distance, ouvrir de nouveaux marchés et aider des entreprises expertes à exprimer un savoir-faire parfois difficile à résumer.",
    economy: "Le bassin de Saint-Dizier porte une histoire industrielle forte, Nogent concentre des métiers liés au métal et aux instruments, Chaumont joue un rôle administratif et culturel, tandis que Langres et Joinville disposent d’atouts patrimoniaux majeurs. Chaque secteur exige un vocabulaire, des preuves et des appels à l’action spécifiques.",
    territory: "La faible densité ne signifie pas une faible demande. Elle modifie les zones de chalandise et rend la recherche en ligne particulièrement utile. Les habitants comparent souvent des professionnels situés dans plusieurs communes ; les entreprises industrielles prospectent à l’échelle nationale ou internationale. Le site doit donc combiner précision locale et capacité à parler au-delà du département.",
    opportunities: "Une présence numérique structurée aide à recruter, convaincre des acheteurs, transmettre un savoir-faire et rendre une destination plus accessible. Les acteurs qui documentent réellement leurs réalisations, leurs procédés ou leur territoire construisent un avantage durable face aux sites institutionnels trop courts ou rarement actualisés.",
    localSeo: "La visibilité passe par une architecture sobre : pages correspondant aux services réels, contenus territoriaux documentés, fiches d’établissement cohérentes, performances mobiles et signaux de confiance. Les données structurées aident Google à comprendre l’organisation, mais elles ne remplacent jamais des informations utiles et vérifiables.",
    approach: "MRD Studio transforme la complexité en parcours simple. Après un audit, nous définissons les messages, les priorités et les preuves. La direction artistique donne une présence singulière, puis le développement garantit rapidité, accessibilité et autonomie. L’accompagnement SEO inscrit le projet dans le temps long.",
    testimonial: { quote: "Notre expertise était difficile à expliquer. Le site la rend enfin accessible et crédible pour nos prospects nationaux.", author: "Élodie B.", company: "Manufacture, bassin nogentais" },
  },
];

export const cityProfiles: Record<string, { department: string; nearby: string[]; focus: string; market: string }> = {
  reims: { department: "marne", nearby: ["Tinqueux", "Cormontreuil", "Bétheny", "Fismes"], focus: "métropole universitaire, maisons de Champagne, cabinets, commerces et entreprises de services", market: "un marché concurrentiel où l’image, les avis et la vitesse du site influencent directement la prise de contact" },
  epernay: { department: "marne", nearby: ["Avize", "Sézanne", "Reims"], focus: "maisons de Champagne, domaines, œnotourisme, hôtellerie et métiers de la vigne", market: "une clientèle française et internationale attentive à l’excellence visuelle et à la réservation mobile" },
  "chalons-en-champagne": { department: "marne", nearby: ["Reims", "Vitry-le-François", "Épernay"], focus: "institutions, collectivités, professions libérales, commerces et PME", market: "un bassin administratif central où la clarté de l’information et l’accessibilité sont essentielles" },
  "vitry-le-francois": { department: "marne", nearby: ["Châlons-en-Champagne", "Saint-Dizier", "Sézanne"], focus: "industrie, logistique, bâtiment, commerce et services de proximité", market: "une zone connectée à plusieurs départements où la visibilité doit dépasser la seule commune" },
  sezanne: { department: "marne", nearby: ["Épernay", "Avize", "Fismes"], focus: "artisans, viticulteurs, commerçants et entreprises familiales", market: "un territoire rural dynamique où Google devient le premier point de comparaison" },
  avize: { department: "marne", nearby: ["Épernay", "Reims", "Sézanne"], focus: "domaines viticoles, Champagne, hébergements et expériences œnotouristiques", market: "le cœur de la Côte des Blancs, avec une exigence d’image internationale et une forte saisonnalité" },
  fismes: { department: "marne", nearby: ["Reims", "Tinqueux", "Soissons"], focus: "artisans, commerces, santé, construction et services locaux", market: "un carrefour entre Reims et Soissons où une zone d’intervention claire soutient le référencement" },
  tinqueux: { department: "marne", nearby: ["Reims", "Cormontreuil", "Bétheny"], focus: "retail, restauration, services et entreprises de l’agglomération rémoise", market: "une continuité urbaine avec Reims qui exige un positionnement précis pour éviter la concurrence sémantique" },
  cormontreuil: { department: "marne", nearby: ["Reims", "Tinqueux", "Bétheny"], focus: "zones commerciales, restauration, automobile, santé et services", market: "un secteur à forte intention d’achat où mobile, horaires et itinéraires doivent être impeccables" },
  betheny: { department: "marne", nearby: ["Reims", "Tinqueux", "Cormontreuil"], focus: "TPE, professions libérales, artisans et services résidentiels", market: "une commune intégrée à l’agglomération rémoise mais dotée de recherches locales propres" },
  "saint-quentin": { department: "aisne", nearby: ["Tergnier", "Chauny", "Hirson"], focus: "industrie, textile, logistique, commerce et services B2B", market: "le premier bassin économique de l’Aisne, connecté aux marchés du nord de la France" },
  laon: { department: "aisne", nearby: ["Soissons", "Saint-Quentin", "Chauny"], focus: "administration, tourisme, professions libérales, santé et commerce", market: "une ville haute patrimoniale et une préfecture où information et confiance structurent les parcours" },
  soissons: { department: "aisne", nearby: ["Laon", "Château-Thierry", "Fismes"], focus: "commerce, agroalimentaire, bâtiment, tourisme et services", market: "un bassin tourné vers Reims et l’Île-de-France, propice à une stratégie de visibilité élargie" },
  "chateau-thierry": { department: "aisne", nearby: ["Soissons", "Épernay", "Reims"], focus: "Champagne, tourisme, restauration, services et entreprises franciliennes décentralisées", market: "la porte sud de l’Aisne, avec des flux vers Paris et la vallée de la Marne" },
  chauny: { department: "aisne", nearby: ["Tergnier", "Saint-Quentin", "Laon"], focus: "industrie, artisanat, bâtiment, commerces et services", market: "un bassin où la réputation locale et la preuve des réalisations orientent fortement le choix" },
  tergnier: { department: "aisne", nearby: ["Chauny", "Saint-Quentin", "Laon"], focus: "transport, industrie, services publics, artisans et commerces", market: "un nœud ferroviaire et économique dont les entreprises rayonnent sur plusieurs communautés de communes" },
  hirson: { department: "aisne", nearby: ["Saint-Quentin", "Charleville-Mézières", "Laon"], focus: "commerce, santé, artisanat, tourisme vert et services transfrontaliers", market: "la Thiérache, territoire étendu où le digital compense les distances et élargit la clientèle" },
  "charleville-mezieres": { department: "ardennes", nearby: ["Sedan", "Nouzonville", "Rethel"], focus: "industrie, culture, services, collectivités et commerce", market: "la capitale ardennaise, au croisement d’un marché local et d’opportunités belges" },
  sedan: { department: "ardennes", nearby: ["Charleville-Mézières", "Rethel", "Givet"], focus: "tourisme patrimonial, industrie, commerce, bâtiment et restauration", market: "une destination connue pour son château et un bassin économique relié à la vallée de la Meuse" },
  rethel: { department: "ardennes", nearby: ["Charleville-Mézières", "Reims", "Sedan"], focus: "agroalimentaire, agriculture, artisanat, commerce et services", market: "le sud des Ardennes, directement connecté au bassin rémois et aux grands axes" },
  givet: { department: "ardennes", nearby: ["Charleville-Mézières", "Nouzonville", "Sedan"], focus: "tourisme, commerce transfrontalier, restauration et industrie", market: "une pointe transfrontalière où les contenus peuvent servir des visiteurs français et belges" },
  nouzonville: { department: "ardennes", nearby: ["Charleville-Mézières", "Sedan", "Givet"], focus: "métallurgie, sous-traitance, artisanat et services de proximité", market: "une commune industrielle de la vallée de la Meuse qui doit valoriser ses savoir-faire techniques" },
  troyes: { department: "aube", nearby: ["Romilly-sur-Seine", "Bar-sur-Seine", "Nogent-sur-Seine"], focus: "retail, textile, tourisme, e-commerce, restauration et enseignement supérieur", market: "une agglomération connue pour ses marques où l’expérience digitale fait partie de la promesse commerciale" },
  "romilly-sur-seine": { department: "aube", nearby: ["Troyes", "Nogent-sur-Seine", "Sézanne"], focus: "industrie, textile, commerce, bâtiment et services", market: "un bassin tourné vers l’Aube, la Marne et la Seine-et-Marne, favorable aux zones de chalandise étendues" },
  "nogent-sur-seine": { department: "aube", nearby: ["Romilly-sur-Seine", "Troyes", "Sézanne"], focus: "énergie, industrie, logistique, agriculture et services B2B", market: "un pôle industriel proche de l’Île-de-France où la crédibilité technique prime" },
  "bar-sur-aube": { department: "aube", nearby: ["Bar-sur-Seine", "Troyes", "Chaumont"], focus: "Champagne, tourisme, hébergement, agriculture et commerce", market: "la Côte des Bar, destination viticole où narration, réservation et visibilité internationale se rencontrent" },
  "bar-sur-seine": { department: "aube", nearby: ["Bar-sur-Aube", "Troyes", "Chaumont"], focus: "viticulture, artisanat, tourisme et services ruraux", market: "un territoire de Champagne dont les acteurs gagnent à professionnaliser leur vente directe" },
  chaumont: { department: "haute-marne", nearby: ["Langres", "Nogent", "Joinville"], focus: "administration, graphisme, industrie, santé, commerce et services", market: "la préfecture haut-marnaise, connue pour son patrimoine graphique et ses fonctions territoriales" },
  langres: { department: "haute-marne", nearby: ["Chaumont", "Nogent", "Dijon"], focus: "tourisme patrimonial, restauration, hébergement, artisanat et commerce", market: "une cité fortifiée dont l’attractivité dépend fortement de la recherche et de la réservation en mobilité" },
  "saint-dizier": { department: "haute-marne", nearby: ["Joinville", "Vitry-le-François", "Chaumont"], focus: "industrie, aéronautique, commerce, bâtiment et services", market: "le principal bassin de population du département, relié à la Marne et à la Meuse" },
  joinville: { department: "haute-marne", nearby: ["Saint-Dizier", "Chaumont", "Nogent"], focus: "patrimoine, tourisme, artisanat, commerce et services locaux", market: "une petite ville à forte identité où le contenu peut transformer la curiosité en visite" },
  nogent: { department: "haute-marne", nearby: ["Chaumont", "Langres", "Joinville"], focus: "coutellerie, instruments, métallurgie, sous-traitance et artisanat d’excellence", market: "un bassin de savoir-faire reconnu nationalement, nécessitant des preuves techniques et une image contemporaine" },
};

export function citySlug(name: string) {
  return name.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/['’]/g, "").replace(/\s+/g, "-");
}

export const blogArticles = [
  ["pourquoi-creer-un-site-internet-en-2026", "Pourquoi créer un site internet en 2026 ?", "Un site propriétaire reste le socle durable d’une présence numérique à l’heure de l’IA, des réseaux sociaux et des recherches locales."],
  ["combien-coute-un-site-internet", "Combien coûte un site internet ?", "Comprendre les écarts de prix entre conception, contenu, développement, SEO, maintenance et création sur mesure."],
  ["site-vitrine-ou-e-commerce", "Site vitrine ou e-commerce ?", "Choisir l’architecture adaptée à votre modèle économique, à votre catalogue et au parcours de vos clients."],
  ["pourquoi-seo-local-indispensable", "Pourquoi le SEO local est indispensable ?", "Transformer les recherches de proximité en visites, appels et demandes qualifiées grâce à une stratégie territoriale."],
  ["comment-choisir-agence-web", "Comment choisir une agence web ?", "Les critères concrets pour évaluer la méthode, les références, la technique, le design et l’accompagnement."],
  ["erreurs-refonte-site", "Les erreurs à éviter lors d’une refonte", "Protéger le référencement, les contenus utiles et les conversions pendant une transformation du site."],
  ["ameliorer-referencement-google", "Comment améliorer son référencement Google ?", "Une méthode progressive fondée sur la technique, l’intention de recherche, la preuve et l’expérience utilisateur."],
  ["google-business-profile", "Google Business Profile : le guide essentiel", "Optimiser sa fiche, ses catégories, ses avis et sa cohérence avec le site pour gagner en visibilité locale."],
  ["seo-pour-artisans", "SEO pour artisans : devenir visible localement", "Présenter ses réalisations, ses zones d’intervention et ses spécialités pour générer des demandes pertinentes."],
  ["seo-pour-restaurants", "SEO pour restaurants : remplir depuis Google", "Menus, données structurées, avis, photos, réservation et contenus locaux au service de la fréquentation."],
  ["seo-domaines-viticoles", "SEO pour domaines viticoles", "Développer la vente directe et l’œnotourisme avec une stratégie adaptée aux domaines de Champagne."],
] as const;
