export type ServiceProfile = {
  slug: string;
  title: string;
  shortTitle: string;
  metaDescription: string;
  lead: string;
  audience: string;
  problem: string;
  promise: string;
  deliverables: string[];
  method: string[];
  faq: [string, string][];
  related: string[];
};

export const serviceProfiles: ServiceProfile[] = [
  {
    slug: "creation-site-internet",
    title: "Création de site internet sur mesure",
    shortTitle: "Création de site internet",
    metaDescription: "Création de sites internet sur mesure avec MRD Studio : stratégie, design, développement Next.js, SEO, performance et accompagnement.",
    lead: "Un site internet efficace ne se résume pas à une belle interface. Il doit expliquer votre valeur, rassurer vos visiteurs, répondre aux exigences des moteurs et faciliter une action concrète. MRD Studio réunit ces dimensions dans un projet conçu autour de votre activité.",
    audience: "Cette prestation s’adresse aux entreprises, artisans, commerces, domaines viticoles et professions libérales qui veulent posséder un outil numérique durable, distinctif et capable d’évoluer.",
    problem: "Les solutions génériques imposent souvent leur structure avant même que les objectifs soient définis. Le résultat peut sembler correct, mais il différencie peu la marque, ralentit la publication et accumule des compromis techniques.",
    promise: "Nous partons des usages, des contenus et du parcours commercial pour construire une architecture claire, une direction visuelle singulière et une base technique mesurable.",
    deliverables: ["Cadrage stratégique et architecture", "UX et direction artistique", "Développement Next.js responsive", "Fondations SEO et données structurées", "Tests, mise en ligne et documentation"],
    method: ["Comprendre l’offre et les publics", "Hiérarchiser les intentions et contenus", "Prototyper les parcours importants", "Concevoir puis développer sur mesure", "Tester la performance et l’accessibilité"],
    faq: [["Quel est le délai moyen ?", "Un site vitrine structuré demande généralement six à dix semaines selon les contenus, les validations et les fonctionnalités."], ["Le site nous appartient-il ?", "Oui. Les conditions de propriété, les accès et les outils utilisés sont précisés dans la proposition avant le démarrage."], ["Pouvez-vous reprendre nos contenus ?", "Nous pouvons auditer, réorganiser et réécrire les contenus existants, ou définir un plan de production avec votre équipe."]],
    related: ["site-vitrine", "site-premium", "optimisation-lighthouse"],
  },
  {
    slug: "refonte-site-internet",
    title: "Refonte de site internet sans perdre votre référencement",
    shortTitle: "Refonte de site",
    metaDescription: "Refonte de site internet : audit UX, migration SEO, nouveau design, redirections, performance et accompagnement avec MRD Studio.",
    lead: "Une refonte sérieuse protège ce qui fonctionne avant de transformer ce qui limite la croissance. Elle commence par un inventaire des URL, du trafic, des contenus, des liens et des conversions, pas par une maquette isolée.",
    audience: "Elle convient aux organisations dont le site ne reflète plus le positionnement, devient difficile à administrer, manque de vitesse ou ne génère plus de demandes satisfaisantes.",
    problem: "Modifier les URL, supprimer des pages utiles ou changer la structure sans plan de migration peut faire disparaître des signaux construits pendant plusieurs années. Une amélioration visuelle peut alors provoquer une régression commerciale.",
    promise: "Nous associons audit, stratégie de migration, design et développement afin que le nouveau site améliore l’expérience tout en conservant la continuité technique et éditoriale.",
    deliverables: ["Audit du site et des performances", "Inventaire SEO et plan de redirections", "Nouvelle architecture et prototypes", "Refonte graphique et développement", "Recette, migration et suivi post-lancement"],
    method: ["Mesurer l’existant", "Identifier les contenus à conserver", "Cartographier chaque ancienne URL", "Tester le nouveau parcours", "Surveiller indexation et erreurs après bascule"],
    faq: [["Faut-il conserver toutes les pages ?", "Non. Chaque page est évaluée selon son utilité, son trafic, ses liens et sa place dans le parcours. Elle peut être conservée, fusionnée ou redirigée."], ["Peut-on refondre progressivement ?", "Oui, si l’architecture le permet. Un découpage par gabarit ou par priorité peut réduire le risque opérationnel."], ["Comment éviter une baisse SEO ?", "Un inventaire complet, des redirections précises, la conservation des contenus utiles et une surveillance après lancement limitent fortement le risque."]],
    related: ["creation-site-internet", "referencement-google", "maintenance-site-internet"],
  },
  {
    slug: "site-vitrine",
    title: "Site vitrine professionnel et orienté conversion",
    shortTitle: "Site vitrine",
    metaDescription: "Création de site vitrine professionnel : design sur mesure, contenus clairs, SEO local, performance mobile et génération de contacts.",
    lead: "Un site vitrine doit permettre de comprendre rapidement qui vous êtes, ce que vous proposez, à qui vous vous adressez et pourquoi vous contacter. Sa simplicité apparente demande une hiérarchie éditoriale particulièrement rigoureuse.",
    audience: "Il répond aux besoins des artisans, consultants, cabinets, PME, restaurants, hébergements et entreprises de services dont la vente commence par une prise de contact.",
    problem: "De nombreux sites vitrines se limitent à quelques blocs génériques. Ils ne traitent pas les objections, n’expliquent pas la méthode et obligent le visiteur à chercher les informations importantes.",
    promise: "Nous créons un parcours compact mais complet, pensé pour le mobile, la recherche locale et la qualification des demandes.",
    deliverables: ["Architecture de pages essentielles", "Design responsive personnalisé", "Formulaires et appels à l’action", "SEO on-page et LocalBusiness", "Outil de mesure respectueux du consentement"],
    method: ["Définir la conversion attendue", "Répondre aux questions avant contact", "Organiser les preuves disponibles", "Optimiser le parcours mobile", "Mesurer appels et formulaires"],
    faq: [["Combien de pages faut-il ?", "Le nombre dépend des services et intentions de recherche. Une page par sujet utile vaut mieux qu’un volume arbitraire."], ["Un site vitrine peut-il bien se référencer ?", "Oui, si ses pages répondent précisément aux recherches, disposent d’une base technique saine et sont enrichies dans le temps."], ["Peut-il évoluer vers la vente en ligne ?", "Une architecture anticipée peut accueillir plus tard un catalogue, une réservation ou un espace client."]],
    related: ["creation-site-internet", "seo-local", "google-business-profile"],
  },
  {
    slug: "site-premium",
    title: "Site internet premium : design, précision et performance",
    shortTitle: "Site premium",
    metaDescription: "Conception de sites internet premium : direction artistique distinctive, expérience immersive, performance et développement sur mesure.",
    lead: "Le premium ne vient ni d’un effet spectaculaire ni d’une accumulation d’animations. Il naît de la cohérence entre la marque, le rythme, la typographie, les contenus, les interactions et la qualité d’exécution.",
    audience: "Cette approche s’adresse aux marques, domaines, établissements et entreprises pour lesquels la perception de qualité influence directement la confiance et la valeur de l’offre.",
    problem: "Une interface luxueuse mais lente ou difficile à lire affaiblit la marque. À l’inverse, une base technique parfaite mais générique ne crée aucune préférence.",
    promise: "MRD Studio équilibre expression visuelle, lisibilité, accessibilité et vitesse pour produire une expérience reconnaissable sans sacrifier l’usage.",
    deliverables: ["Territoire visuel digital", "Système typographique et composants", "Prototypes interactifs", "Animations sobres et performantes", "Développement et contrôle qualité"],
    method: ["Clarifier les codes de marque", "Définir une signature visuelle", "Tester la hiérarchie sans effets", "Ajouter le mouvement au service du contenu", "Contrôler chaque breakpoint"],
    faq: [["Qu’est-ce qui rend un site premium ?", "La pertinence de la direction artistique, la qualité des détails, la cohérence du contenu et la fluidité technique, pas une technologie isolée."], ["Les animations ralentissent-elles le site ?", "Elles peuvent rester légères lorsqu’elles utilisent principalement transform et opacity et respectent la réduction des mouvements."], ["Le design reste-t-il accessible ?", "Oui. Contraste, clavier, structure sémantique et lisibilité sont intégrés dès la conception."]],
    related: ["creation-identite-visuelle", "optimisation-lighthouse", "creation-site-internet"],
  },
  {
    slug: "seo-local",
    title: "SEO local pour développer votre visibilité de proximité",
    shortTitle: "SEO local",
    metaDescription: "SEO local : architecture, pages géographiques utiles, Google Business Profile, données structurées et suivi des demandes locales.",
    lead: "Le SEO local relie une activité réelle aux recherches effectuées dans sa zone de chalandise. Il ne consiste pas à répéter des noms de villes, mais à démontrer une présence, une expertise et une capacité d’intervention crédibles.",
    audience: "Il concerne les entreprises recevant du public, se déplaçant chez leurs clients ou travaillant dans plusieurs bassins économiques.",
    problem: "Des coordonnées incohérentes, des pages interchangeables et une fiche d’établissement négligée brouillent les signaux. Le site et les plateformes locales doivent raconter la même réalité.",
    promise: "Nous structurons les services, territoires, contenus et données d’entreprise pour renforcer la pertinence sans créer de pages artificielles.",
    deliverables: ["Audit de visibilité locale", "Architecture services et zones", "Optimisation Google Business Profile", "Balisage LocalBusiness", "Plan éditorial et mesure des contacts"],
    method: ["Cartographier les zones réellement servies", "Analyser les intentions par métier", "Créer des contenus territoriaux utiles", "Harmoniser les informations d’entreprise", "Suivre appels, itinéraires et formulaires"],
    faq: [["Faut-il une page pour chaque ville ?", "Seulement si l’entreprise y intervient réellement et si la page apporte des informations spécifiques au marché et au visiteur."], ["Quand voit-on des résultats ?", "Le délai varie selon la concurrence, l’historique du domaine et les signaux locaux. Le SEO se pilote sur plusieurs mois."], ["La fiche Google suffit-elle ?", "Non. Elle facilite la découverte, tandis que le site développe les services, les preuves et les réponses nécessaires à la décision."]],
    related: ["google-business-profile", "referencement-google", "site-vitrine"],
  },
  {
    slug: "referencement-google",
    title: "Référencement Google fondé sur la qualité et la mesure",
    shortTitle: "Référencement Google",
    metaDescription: "Accompagnement référencement Google : audit technique, stratégie de contenus, maillage, données structurées et mesure des conversions.",
    lead: "Google cherche à explorer une page, comprendre son intention et évaluer si elle peut satisfaire l’utilisateur. Le référencement durable travaille ces trois dimensions au lieu de chercher une astuce isolée.",
    audience: "L’accompagnement convient aux sites qui veulent structurer leur croissance organique, corriger une stagnation ou préparer une refonte sans perdre leurs acquis.",
    problem: "Publier beaucoup sans stratégie crée des pages qui se concurrencent. Corriger uniquement la technique ne suffit pas davantage si le contenu reste vague ou si l’autorité est absente.",
    promise: "Nous priorisons les actions selon leur impact attendu, leur faisabilité et leur relation avec les objectifs commerciaux.",
    deliverables: ["Audit crawl, indexation et contenus", "Recherche d’intentions", "Plan de pages et maillage interne", "Optimisations on-page", "Tableau de bord et feuille de route"],
    method: ["Rendre le site explorable", "Consolider les URL concurrentes", "Répondre à des intentions précises", "Renforcer expertise et preuves", "Mesurer les conversions organiques"],
    faq: [["Garantissez-vous une première position ?", "Non. Aucun prestataire sérieux ne contrôle l’algorithme, la concurrence ou les résultats. Nous garantissons une méthode et des livrables vérifiables."], ["Faut-il publier chaque semaine ?", "La fréquence doit rester compatible avec la capacité à produire un contenu utile, original et maintenu."], ["Travaillez-vous aussi Bing ?", "Une architecture claire, les sitemaps et les données structurées servent plusieurs moteurs. Bing Webmaster Tools et IndexNow peuvent compléter le dispositif."]],
    related: ["seo-local", "optimisation-lighthouse", "refonte-site-internet"],
  },
  {
    slug: "maintenance-site-internet",
    title: "Maintenance de site internet et accompagnement continu",
    shortTitle: "Maintenance",
    metaDescription: "Maintenance de site internet : mises à jour, sécurité, sauvegardes, surveillance, corrections et évolutions documentées.",
    lead: "La mise en ligne marque le début de la vie du site. Les dépendances évoluent, les contenus changent et de nouveaux besoins apparaissent. Une maintenance organisée évite que les petites anomalies deviennent des risques.",
    audience: "Elle s’adresse aux organisations qui veulent déléguer la surveillance technique tout en gardant une visibilité claire sur les interventions.",
    problem: "Une maintenance purement réactive intervient trop tard. Sans suivi des erreurs, des formulaires et des performances, une dégradation peut rester invisible pendant plusieurs semaines.",
    promise: "Nous définissons un périmètre, une fréquence et un processus d’escalade adaptés à la criticité du site.",
    deliverables: ["Mises à jour contrôlées", "Surveillance de disponibilité", "Sauvegardes et procédure de restauration", "Correction d’incidents", "Rapport d’interventions et évolutions"],
    method: ["Inventorier la stack et les accès", "Définir les niveaux de priorité", "Tester avant mise à jour", "Surveiller les parcours critiques", "Documenter chaque intervention"],
    faq: [["La maintenance inclut-elle l’hébergement ?", "Elle peut l’inclure ou fonctionner avec votre hébergeur actuel. Le périmètre est défini au contrat."], ["Intervenez-vous sur tous les sites ?", "Un audit préalable vérifie la technologie, la qualité du code et les accès avant toute reprise."], ["Peut-on demander des évolutions ?", "Oui. Les évolutions sont estimées séparément ou incluses dans une enveloppe définie."]],
    related: ["optimisation-lighthouse", "refonte-site-internet", "creation-site-internet"],
  },
  {
    slug: "optimisation-lighthouse",
    title: "Optimisation Lighthouse et Core Web Vitals",
    shortTitle: "Optimisation Lighthouse",
    metaDescription: "Optimisation Lighthouse : LCP, INP, CLS, images, JavaScript, accessibilité et bonnes pratiques pour une expérience rapide.",
    lead: "Un score Lighthouse est un diagnostic de laboratoire, pas une fin en soi. L’objectif réel consiste à accélérer l’affichage utile, stabiliser la page et rendre chaque interaction réactive sur les appareils de vos visiteurs.",
    audience: "Cette prestation aide les sites lents, les refontes avant lancement et les équipes qui veulent améliorer leurs Core Web Vitals sans détériorer le design.",
    problem: "Compresser quelques images ne corrige pas une architecture JavaScript trop lourde, un serveur lent ou une police bloquante. Chaque métrique possède plusieurs causes possibles.",
    promise: "Nous mesurons, identifions les goulots puis corrigeons par ordre d’impact, avec comparaison avant et après.",
    deliverables: ["Audit Lighthouse et données terrain", "Analyse LCP, INP et CLS", "Optimisation images et polices", "Réduction du JavaScript critique", "Rapport de mesures et recommandations"],
    method: ["Séparer laboratoire et terrain", "Identifier l’élément LCP", "Réduire le travail du thread principal", "Réserver l’espace des médias", "Contrôler les régressions"],
    faq: [["Garantissez-vous un score de 100 ?", "Non. Le score dépend du contexte, des scripts tiers et de l’environnement de test. Nous privilégions les améliorations perceptibles et stables."], ["Faut-il supprimer les animations ?", "Pas nécessairement. Des animations sobres basées sur transform et opacity peuvent rester fluides."], ["Les performances influencent-elles le SEO ?", "Elles participent à l’expérience globale et aux Core Web Vitals, mais ne remplacent ni la pertinence ni l’autorité du contenu."]],
    related: ["creation-site-internet", "maintenance-site-internet", "referencement-google"],
  },
  {
    slug: "creation-identite-visuelle",
    title: "Création d’identité visuelle pensée pour le digital",
    shortTitle: "Identité visuelle",
    metaDescription: "Création d’identité visuelle : positionnement, logo, couleurs, typographies, système graphique et déclinaisons digitales cohérentes.",
    lead: "Une identité visuelle utile permet d’être reconnu, de rester cohérent et de produire de nouveaux supports sans repartir de zéro. Elle traduit un positionnement en règles graphiques utilisables.",
    audience: "Elle accompagne les créations d’entreprise, repositionnements et refontes dont l’univers actuel ne correspond plus à la qualité de l’offre.",
    problem: "Un logo isolé ne suffit pas. Sans règles de composition, de typographie, de couleur et d’image, chaque support finit par raconter une marque différente.",
    promise: "Nous construisons un système adapté aux écrans, aux usages commerciaux et aux capacités réelles de votre équipe.",
    deliverables: ["Cadrage de marque", "Pistes créatives argumentées", "Logo et variantes", "Palette et typographies", "Guide d’usage et composants digitaux"],
    method: ["Clarifier la perception recherchée", "Étudier le contexte concurrentiel", "Explorer plusieurs territoires", "Tester la lisibilité réelle", "Documenter les usages"],
    faq: [["Créez-vous uniquement un logo ?", "Nous privilégions un système complet, car la cohérence d’une marque dépend de l’ensemble de ses règles."], ["L’identité fonctionne-t-elle pour l’impression ?", "Les livrables peuvent prévoir les déclinaisons numériques et imprimées selon les besoins."], ["Peut-elle être créée avec le site ?", "Oui. Travailler les deux ensemble permet d’éprouver immédiatement le système dans une interface réelle."]],
    related: ["site-premium", "creation-site-internet", "gestion-reseaux-sociaux"],
  },
  {
    slug: "gestion-reseaux-sociaux",
    title: "Gestion des réseaux sociaux avec une ligne éditoriale claire",
    shortTitle: "Gestion réseaux sociaux",
    metaDescription: "Gestion des réseaux sociaux : stratégie, calendrier éditorial, création de contenus, publication, modération et analyse.",
    lead: "Une présence sociale régulière demande davantage qu’un calendrier rempli. Chaque plateforme doit avoir un rôle, un public, des formats et des indicateurs reliés à la stratégie globale.",
    audience: "L’accompagnement concerne les entreprises qui manquent de temps, de cohérence ou de méthode pour animer leurs comptes.",
    problem: "Publier sans objectif disperse les ressources. Une audience peut progresser sans générer de notoriété utile, de trafic qualifié ou de conversations commerciales.",
    promise: "Nous définissons une ligne éditoriale réaliste, des séries reconnaissables et un processus de validation compatible avec votre organisation.",
    deliverables: ["Audit des comptes", "Stratégie par plateforme", "Calendrier et production", "Publication et modération", "Analyse mensuelle"],
    method: ["Définir le rôle de chaque canal", "Identifier les ressources disponibles", "Créer des formats répétables", "Organiser la validation", "Mesurer au-delà des impressions"],
    faq: [["Sur quelles plateformes intervenez-vous ?", "Le choix dépend de vos publics et ressources. Être présent partout n’est pas un objectif en soi."], ["Faut-il publier tous les jours ?", "Non. Une fréquence soutenable et qualitative est préférable à une présence intensive puis interrompue."], ["Le site reste-t-il important ?", "Oui. Les réseaux distribuent les contenus, tandis que le site reste l’espace maîtrisé pour approfondir et convertir."]],
    related: ["community-management", "creation-identite-visuelle", "creation-site-internet"],
  },
  {
    slug: "community-management",
    title: "Community management et relation de marque",
    shortTitle: "Community management",
    metaDescription: "Community management : animation, modération, réponses, veille et gestion des conversations pour une présence de marque cohérente.",
    lead: "Le community management représente la marque dans des échanges publics et immédiats. La qualité des réponses, la cohérence du ton et la vitesse de traitement influencent directement la confiance.",
    audience: "Il s’adresse aux marques recevant des commentaires, questions et messages réguliers qu’elles souhaitent traiter avec méthode.",
    problem: "Répondre au cas par cas sans cadre crée des écarts de ton et augmente le risque lors d’une critique ou d’une situation sensible.",
    promise: "Nous mettons en place des règles de réponse, un circuit d’escalade et une veille qui protègent la relation sans automatiser artificiellement la conversation.",
    deliverables: ["Charte de modération", "Bibliothèque de réponses", "Animation des conversations", "Veille et signalement", "Rapport des sujets récurrents"],
    method: ["Définir le ton et les limites", "Classer les demandes", "Préparer les situations sensibles", "Répondre avec contexte", "Faire remonter les enseignements"],
    faq: [["Répondez-vous aux messages privés ?", "Oui, selon le périmètre, les horaires et les informations que votre équipe peut transmettre."], ["Comment gérez-vous un commentaire négatif ?", "Nous distinguons critique légitime, demande de support et abus, puis suivons une procédure validée avec vous."], ["Pouvez-vous garantir l’absence de crise ?", "Non. Nous réduisons le risque par la préparation, la veille et une escalade rapide."]],
    related: ["gestion-reseaux-sociaux", "creation-identite-visuelle", "google-business-profile"],
  },
  {
    slug: "google-business-profile",
    title: "Optimisation Google Business Profile",
    shortTitle: "Google Business Profile",
    metaDescription: "Optimisation Google Business Profile : catégories, services, informations, photos, avis authentiques et cohérence avec votre site.",
    lead: "La fiche Google Business Profile est souvent le premier contact avec une entreprise locale. Elle doit fournir des informations exactes, faciliter l’action et rester cohérente avec le site.",
    audience: "Elle est essentielle aux établissements accueillant du public et aux entreprises intervenant dans une zone définie.",
    problem: "Catégories imprécises, doublons, horaires obsolètes ou changements non contrôlés réduisent la confiance et peuvent perturber la visibilité locale.",
    promise: "Nous optimisons uniquement les informations réelles, organisons le suivi et relions la fiche à une stratégie locale plus large.",
    deliverables: ["Audit de la fiche et des doublons", "Catégories et services", "Informations et liens suivis", "Plan de photos et publications", "Processus d’avis authentiques"],
    method: ["Vérifier la propriété et les accès", "Aligner les coordonnées", "Choisir les catégories factuelles", "Préparer les contenus utiles", "Suivre appels, itinéraires et site"],
    faq: [["Pouvez-vous créer de faux avis ?", "Non. Nous aidons à solliciter des retours authentiques sans contrepartie ni sélection trompeuse."], ["La fiche garantit-elle une position ?", "Non. La proximité, la pertinence et la notoriété dépendent de nombreux signaux que personne ne contrôle seul."], ["Faut-il publier régulièrement ?", "Des mises à jour utiles peuvent aider les visiteurs, mais l’exactitude des informations et la qualité globale restent prioritaires."]],
    related: ["seo-local", "community-management", "site-vitrine"],
  },
];

export const serviceBySlug = Object.fromEntries(
  serviceProfiles.map((service) => [service.slug, service]),
) as Record<string, ServiceProfile>;
